<?php include('../application/default/views/scripts/all_header.phtml'); ?>

<?php include('../application/default/views/scripts/all_begin.phtml'); ?>

<?php include('../application/default/views/scripts/all_menu.phtml'); ?>

<?php include('../application/default/views/scripts/all_nav.phtml'); ?>


            <div id="stred">
                <?=$this->txt[$this->kod]?>
            	
	            <div class="cistic"></div>

                
           	
           	</div><!-- stred -->
        
        	<div class="cistic"></div>
        </div><!-- obsah -->
        <div class="cistic"></div>

            

<?php include('../application/default/views/scripts/all_footer.phtml'); ?>

