<?php include('../application/default/views/scripts/all_header.phtml'); ?>

<?php include('../application/default/views/scripts/all_begin.phtml'); ?>

<?php include('../application/default/views/scripts/all_menu.phtml'); ?>

<?php include('../application/default/views/scripts/all_nav.phtml'); ?>

<?php
$_SESSION['crumb-text'] = '';
?>
        
           <div id="stred">
				<div id="cart">
            		<span><a href="/obchod/kosik/ukaz"><?= vp($_t->_('nakupni kosik'))?></a></span> <span><a href="/obchod/kosik/doprava"><?= vp($_t->_('doprava a platba'))?></a></span>
            		 <h1><span><?= vp($_t->_('udaje o objednateli'))?></span></h1> <span><?= vp($_t->_('shrnuti objednavky'))?></span>
				</div><!-- cart -->
				
				<div class="cistic"></div>
              	<?php if (!isset($_SESSION['uzivatel']['login']) || trim($_SESSION['uzivatel']['login']) == '') :?>
               		<p><strong class="red"><?= vp($_t->_('nejste prihlasen'))?>.</strong>
                	<?= vp($_t->_('pokud jste jiz zaregistrovan'))?>, <strong><?= ($_t->_('prihlaste se'))?></strong> 
                	<?= vp($_t->_('vpravo nahore pro zobrazeni cen vasi odberatelske skupiny'))?>.</p>
                <?php endif ?>
				
                <form id="objednatel" class="formular" action="/obchod/kosik/zpracujdoruceni" method="post">
                <h2 class="legend"><?= vp($_t->_('udaje o zakaznikovi'))?></h2>
             	<fieldset>                    
                	<label for="jmeno"><?= vp($_t->_('jmeno'))?>:*</label> <input type="text" size="50" class="middle" name="jmeno" id="jmeno" readonly="readonly" value="<?= $this->osoba['osoba'];?>"/>                    
                    <div class="cistic"></div>
                   <label for="email"><?= vp($_t->_('email'))?>:*</label> <input type="text" size="30" class="middle" name="email" id="email" readonly="readonly" value="<?= $this->osoba['email'];?>" />
                    <label for="telefon"><?= vp($_t->_('telefon'))?>:*</label> <input type="text" size="30" class="short" name="telefon" id="telefon" readonly="readonly" value="<?= $this->osoba['telefon'];?>" />
                   <div class="cistic"></div>
                   <a href="/obchod/pristup/editace/fromobj/ano/#zakaznik"><?= vp($_t->_('zmenit udaje o zakaznikovi'))?></a>
                </fieldset>	
                
                <h2 class="legend"><?= vp($_t->_('fakturacni adresa'))?></h2>
                <fieldset>   
                	<label for="firma"><?= vp($_t->_('firma'))?>:</label> <input type="text" size="50" class="middle" name="firma" id="firma" readonly="readonly" value="<?= $this->firma['nazev_firmy'];?>" />
					<label for="ic" class="uzsi"> <?= vp($_t->_('IC'))?>:</label> <input type="text" size="30" class="short mr30" name="ic" id="ic" readonly="readonly" value="<?= $this->firma['ico'];?>" />
					<label for="dic" class="uzsi"><?= vp($_t->_('DIC'))?>:</label> <input type="text" size="30" class="short" name="dic" id="dic" readonly="readonly" value="<?= $this->firma['dic'];?>" />
					  <div class="cistic"></div>
					<label for="ulice"><?= vp($_t->_('ulice'))?>:*</label> <input type="text" size="50" class="middle" name="ulice" id="ulice" readonly="readonly" value="<?= $this->firma['ulice'];?>" />
                    <div class="cistic"></div>
                   <label for="mesto"><?= vp($_t->_('mesto'))?>:*</label> <input type="text" size="50" class="middle" name="mesto" id="mesto" readonly="readonly" value="<?= $this->firma['mesto'];?>" />
                   <label for="psc" class="uzsi"><?= vp($_t->_('psc'))?>:*</label> <input type="text" size="30" class="short mr30" name="psc" id="psc" readonly="readonly" value="<?= $this->firma['psc'];?>" />
                    <label for="stat" class="uzsi"><?= vp($_t->_('stat'))?>:*</label> 
                     <select name="stat" id="stat" readonly="readonly">
                     	<option><?= vp($_t->_('vyberte'))?></option>
                        <option value="cz"<?php if ($this->firma['stat'] == 'Česká republika') echo ' selected="selected"';?>><?= vp($_t->_('ceska republika'))?></option>
                        <option value="sk"<?php if ($this->firma['stat'] == 'Slovenská republika') echo ' selected="selected"';?>><?= vp($_t->_('slovenska republika'))?></option>
                     </select> 
                   <div class="cistic"></div>
                   <a href="/obchod/pristup/editace/fromobj/ano/#fakturace"><?= vp($_t->_('zmenit fakturacni udaje'))?></a>
             	</fieldset>	
                
                <h2 class="legend"><?= vp($_t->_('dodaci adresa'))?>, <?= vp($_t->_('pokud je odlisna od fakturacni adresy'))?></h2>                
                <fieldset class="mb0">   
                	<input type="hidden" id="lisise" name="lisise" value="<?= $this->doruceni['lisise'];?>" />                 
                	<label for="jmeno2"><?= vp($_t->_('jmeno'))?>:</label> <input type="text" size="50" class="middle" name="jmeno2" id="jmeno2" value="<?= $this->doruceni['osoba'];?>" />
                    <label for="firma2" class="uzsi"><?= vp($_t->_('firma'))?>:</label> <input type="text" size="50" class="middle" name="firma2" id="firma2" value="<?= $this->doruceni['nazev_firmy'];?>" /> 
                    <label for="cp2" class="uzsi"><?= vp($_t->_('c.p.'))?>:</label> <input type="text" size="30" class="short2" name="cp2" id="cp2" />
                    <div class="cistic"></div>
                    
                    <label for="ulice2"><?= vp($_t->_('ulice'))?>:</label> <input type="text" size="50" class="middle" name="ulice2" id="ulice2" value="<?= $this->doruceni['ulice'];?>" />
                     <label for="mesto2" class="uzsi"><?= vp($_t->_('mesto'))?>:</label> <input type="text" size="50" class="middle" name="mesto2" id="mesto2" value="<?= $this->doruceni['mesto'];?>" />                    
                   <label for="psc2" class="uzsi"><?= vp($_t->_('psc'))?>:</label> <input type="text" size="30" class="short2" name="psc2" id="psc2" value="<?= $this->doruceni['psc'];?>" />
                    
                   <div class="cistic"></div>
                   <a href="/obchod/pristup/editace/fromobj/ano/#dodani"><?= vp($_t->_('zmenit dodaci adresu'))?></a>
             	</fieldset>	               
                
                <h2 class="legend"><?= vp($_t->_('ostatni informace'))?></h2> 
                  <fieldset class="mb0">                    
                	<label for="kupon" class="sirsi"><?= vp($_t->_('slevovy kupon'))?>:</label> <input type="text" size="50" class="middle" name="kupon" id="kupon" />
                        <span id="kupon-chyba" style="font-weight:bold;color:red;"></span><span id="kupon-hlaska"></span>
                        <input type="hidden" id="kupon-sleva" name="kupon-sleva" value="0"/>
                    <div class="cistic"></div>                 
                    <label for="poznamky" class="sirsi"><?= vp($_t->_('poznamky'))?>:</label> <textarea name="poznamky" id="poznamky" rows="10" cols="30"></textarea>                   
             	</fieldset>	
                <div class="small">*<?= vp($_t->_('poviny udaj'))?></div>
             	
                <div id="podminky">
                    <input type="checkbox" name="souhlas" id="souhlas" /> <span class="velky"><?= vp($_t->_('souhlasim s'))?> <a href="/web/texty/zobraz/idt/podminky"><?= ($_t->_('obchodnimi podminkami'))?></a></span><br />               
             </div>

					<a href="/obchod/kosik/doprava" class="pokracovat"><?= vp($_t->_('doprava a platba'))?></a>
					<?php if (sizeof($_SESSION['kosik']) > 0 && isset($_SESSION['uzivatel']['login']) && trim($_SESSION['uzivatel']['login']) != ''):?>
						<a id="dorucenipokladna" href="#" class="kpokladne"><?= vp($_t->_('k pokladne'))?></a>
					<?php endif?>
			</form>
                
           	<div class="cistic"></div>
           	<?=$this->txt[$this->kod_txt]?>
            </div><!-- stred -->
        
        	<div class="cistic"></div>
        </div><!-- obsah -->
        <div class="cistic"></div>

<?php
$pov = array(
	'jmeno' => $_t->_('jmeno'),
	'email' => $_t->_('email'),
	'telefon' => $_t->_('telefon'),
	'ulice' => $_t->_('ulice'),
	'mesto' => $_t->_('mesto'),
	'psc' => $_t->_('psc'),
	'stat' => $_t->_('stat')
);
$dor = array(
	'ulice2' => $_t->_('ulice doruceni'),
	'mesto2' => $_t->_('mesto doruceni'),
	'psc2' => $_t->_('psc doruceni')
);
//vyhodnoceni formulare
?>
<script type="text/javascript">
function OverFormularDoruceni(e) {
	Nepracuji();
	var varovani = '<?=vp($_t->_('vyplneni nize uvedenych poli je povinne'));?>';
	var chyba = false;
	<?php
		foreach($pov as $k => $h) {
			echo "if (dojo.byId('$k').value == '') {chyba = true; varovani += '\\n- $h';}\n";
		}
	?>
	if (dojo.byId('lisise').value == 'ano') {
		<?php
			foreach($dor as $k => $h) {
				echo "if (dojo.byId('$k').value == '') {chyba = true; varovani += '\\n- $h';}\n";
			}
		?>
	}
	if (!dojo.byId('souhlas').checked) {
		chyba = true;
		varovani += '\n- <?=($_t->_('je treba souhlasit s obchodnimi podminkami naseho obchodu'));?>';
	}
	dojo.stopEvent(e);
	if (chyba) {
		alert(varovani);
	} else { //je to v poradku, muze se odeslat formular
		dojo.byId('objednatel').submit();
	}
}

function OverKupon(e) {
        if (<?=$_SESSION['objemova_sleva']?> != 0 && String(dojo.byId('kupon').value) != '') {
            if (!confirm('<?=vp($_t->_('existuje mnozstevni sleva'))?>')) {
                dojo.byId('kupon').value = '';
                dojo.byId('kupon-sleva').value = 0;
                return;
            }
        }
        if (String(dojo.byId('kupon').value) == '') {
            dojo.byId('kupon').value = '';
            dojo.byId('kupon-sleva').value = 0;
            dojo.byId('kupon-chyba').innerHTML = '';
            dojo.byId('kupon-hlaska').innerHTML = '';
            return;
        }
	Pracuji();
	dojo.xhrGet({
		url: "/admin/ajax/nacti/prikaz/overkupon/pn1/cislo_kuponu/ph1/" + String(dojo.byId('kupon').value),
		handleAs: "json",
		load: function(data,args){
			console.debug('Pocet nalezenych kuponu: ' + data.k.row.pocet);
			if (data.k.row.pocet != '0') {
				dojo.byId('kupon-chyba').innerHTML = '';
				dojo.byId('kupon-hlaska').innerHTML = '<?=vp($_t->_('sleva z kuponu'))?>: ' + data.s.row.sleva + '%';
				dojo.byId('kupon-sleva').value = data.s.row.sleva;
        			console.debug('Nalezena sleva: ' + data.s.row.sleva);
			} else {
				dojo.byId('kupon-chyba').innerHTML = '<?=vp($_t->_('neplatny kupon'))?>!';
				dojo.byId('kupon-hlaska').innerHTML = '';
				dojo.byId('kupon-sleva').value = '0';
			}
			Nepracuji();
		},
		// if any error occurs, it goes here:
		error: function(error,args){
			console.warn("Chyba pri overovani kuponu: ",error);
			Nepracuji();
		}
	});
}

dojo.addOnLoad(function() {
        if (dojo.byId('dorucenipokladna')) {
            dojo.connect(dojo.byId('dorucenipokladna'), 'onclick', OverFormularDoruceni);
        }
	if (dojo.byId('kupon')) {
            dojo.connect(dojo.byId('kupon'), 'onchange', OverKupon);
        }
});
</script>


<?php include('../application/default/views/scripts/all_footer.phtml'); ?>

